thewoowon/20230306-thewoowon.md
```python
def plusTenMinute(time):
sp = time.split(":")
hour = int(sp[0])
minute = int(sp[1]) + 10
if minute >= 60:
hour += 1
minute -= 60
return str(hour).zfill(2) + ":" + str(minute).zfill(2)
def solution(book_time):
book_time.sort()
tails = []
for book in book_time:
if tails:
for tail in tails:
if tail[-1] < book[0] and plusTenMinute(tail[-1]) <= book[0]:
tail.append(book[1])
break
else:
tails.append([book[1]])
else:
tails.append([book[1]])
return len(tails)
```
- 예약 시작 시간 기준으로 오름차순 정렬
- 10분을 더하는 기능 분리 및 함수 생성
주의! : 예약 시작 시간이 24시 안에만 있기 때문에 23:59분 이후의 시간을 굳이 00:07 이런 식으로 계산 안해도 됨.
그래서 그냥 10분만 더해 주고 다시 문자열로만 반환.
- tails라는 2차원 배열 생성, 비어 있으면 방을 배정하고 단지 예약 마감 시간만 바라보면 됨.
주의! : 후번의 주자는 예약 시작 시간을 신경쓰지 않아도 됨.
- 오름차순 정렬된 book의 시작 시간과 tails의 시간들을 이중 for문을 활용해 순회.
- 청소까지 끝나는 시간이 나의 시작 시간보다 작거나 …
=> SOLVERTIC solve: 호텔 대실

tkdlqh2/20230306-tkdlqh2.md
```java
import java.util.*;
import java.util.stream.*;
public class Solve0306 {
class BookTime {
public int inHour;
public int inMinute;
public int outHour;
public int outMinute;
BookTime(String[] book_time){
this.inHour = Integer.parseInt(book_time[0].split(":")[0]);
this.inMinute = Integer.parseInt(book_time[0].split(":")[1]);
this.outHour = Integer.parseInt(book_time[1].split(":")[0]);
this.outMinute = Integer.parseInt(book_time[1].split(":")[1]);
}
}
public int solution(String[][] book_time) {
List<BookTime> bookTimeList= IntStream.range(0,book_time.length)
.mapToObj(x-> new BookTime(book_time[x]))
.sorted((x,y) -> {
if(x.inHour == y.inHour){
return x.inMinute -y.inMinute;
}
return x.inHour-y.inHour;
})
.collect(Collectors.toList());
PriorityQueue<BookTime> pq = new …
```
=> SOLVERTIC solve : 호텔 대실

tkdlqh2/20230307-tkdlqh2.md
```java
public int[] solution(int[][] users, int[] emoticons) {
int[] log = new int[emoticons.length];
int[] answer = new int[2];
for (int i = 0; i < 4; i++) {
int[] cur = dfs(0, (i + 1) * 10, users, emoticons, log);
if (cur[0] > answer[0] || (cur[0] == answer[0] && cur[1] > answer[1])) {
answer = cur;
}
}
return answer;
}
public int[] dfs(int depth, int discountRate, int[][] users, int[] emoticons, int[] log) {
if (depth == emoticons.length - 1) {
log[depth] = discountRate;
int[] answer = new int[2];
for (int i = 0; i < users.length; i++) {
int dcCriteria = users[i][0];
int ticketCriteria = users[i][1];
int userTotal = 0;
for (int j = 0; j < emoticons.length; j++) {
if (log[j] >= dcCriteria) {
userTotal += emoticons[j] * (100 - log[j]) / 100;
}
}
if (userTotal >= …
```
=> SOLVERTIC solve: 이모티콘 할인행사

thewoowon/20230308-thewoowon.md
```python
class Node(object):
def __init__(self, info):
self.value = info[2]
self.pos = info[:2]
self.left = None
self.right = None
def add_node(parent, info):
if parent.pos[0] > info[0]:
if parent.left:
add_node(parent.left, info)
else:
parent.left = Node(info)
else:
if parent.right:
add_node(parent.right, info)
else:
parent.right = Node(info)
def solution(nodeinfo):
answer = [[]]
for index in range(len(nodeinfo)):
nodeinfo[index].append(index + 1)
nodeinfo.sort(key=lambda x: (-x[1], x[0]))
t = Node(nodeinfo[0])
for info in nodeinfo[1:]:
add_node(t, info)
return [pre_order(t), post_order(t)]
def pre_order(curr):
path = [curr.value]
if curr.left:
path += pre_order(curr.left)
if curr.right:
path += pre_order(curr.right)
return path
def post_order(curr):
path = []
if curr.left:
path += …
```
=> SOLVERTIC solve: 길 찾기 게임

tkdlqh2/20230308-tkdlqh2.md
```java
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
public int[][] solution(int[][] nodeinfo) {
List<Node> nodeList = new ArrayList<>(nodeinfo.length);
for (int i = 0; i < nodeinfo.length; i++) {
nodeList.add(new Node(i + 1, nodeinfo[i][0], nodeinfo[i][1]));
}
nodeList.sort((first,second) -> {
if(first.y == second.y){
return first.x - second.x;
}else{
return second.y - first.y;
}
});
Tree tree = new Tree(nodeList.get(0));
for (int i = 1; i < nodeList.size(); i++) {
tree.addNode(nodeList.get(i));
}
int[][] answer = new int[2][nodeinfo.length];
answer[0] = tree.preOrderList();
answer[1] = tree.postOrderList();
return answer;
}
class Node{
public int num;
public int x;
public int y;
public Node left;
public Node right;
Node(int num, int x, …
```
=> SOLVERTIC solve : 길찾기 게임

yg0585/20230309-yg0585.md
```java
public int solution(int storey) {
int result = 0;
while(storey > 0) {
int remainder = storey % 10;
storey /= 10;
if (remainder >= 6 || (remainder == 5 && storey % 10 >= 5)) {
result += 10 - remainder;
storey++;
}
else
result += remainder;
}
return result;
}
}
```
일의 자리가 5가 넘으면 올라가서 더 큰 단위의 숫자로 내려오는 것이 더 빠르기 때문에 이 기준을 분기삼아 케이스를 나눠줍니다.
한 가지 더 생각할 점은 지금 1의 자리만 볼 것이 아니라 1의 자리가 올라갔을 때 10의 자리까지 생각해줘야 한다는 점이네요.
처음에 DFS로 하다가 Stack Overflow 나서 위 방법으로 바꿨는데 세 개의 테스트 케이스가 통과하지 않았습니다.
그래서 테스트 케이스 한 20개쯤 추가하다 반례를 찾았고, 10의 자리도 고려하는 if문 추가하는 것도 넣어줬습니다.
결론적으로 성공적으로 풀긴했지만, 문제를 품에 있어서 처음부터 올바른 접근을 할 수 있는 능력이 있으면 좋겠네요.
=> SOLVERTIC solve: 마법의 엘리베이터

yg0585/20230312-yg0585.md
```java
public int[] solution(int[] numbers) {
int[] answer = new int[numbers.length];
answer[numbers.length - 1] = -1;
int[] temp = numbers.clone();
Arrays.sort(temp);
int maxIndex = numbers.length - 1;
for (int i = 0; i < numbers.length - 1; i++) {
int num = -1;
if (i >= 1 && numbers[i] == numbers[i - 1])
num = answer[i - 1];
else if (temp[maxIndex] != numbers[i]) {
for (int j = i + 1; j < numbers.length; j++) {
if (numbers[j] > numbers[i]) {
num = numbers[j];
break;
}
}
} else
maxIndex--;
answer[i] = num;
}
return answer;
}
}
}
```
for 문 두개를 사용해서 계속 뒤의 최대값 찾으면 update 하도록 구현했습니다.
위 코드로 하니까 1개의 테스트 케이스 오류가 났습니다.. 결국 못고치고 풀이를 봤는데 스택을 사용해서 for문 하나로 끝내더군요. 왜 이걸 생각을 못했나 싶었습니다...
=> SOLVERTIC solve: 뒤에 있는 큰 수 찾기

tkdlqh2/20230311-tkdlqh2.md, tkdlqh2/20230312-tkdlqh2.md, tkdlqh2/20230313-tkdlqh2.md
```java
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
public int solution(int[] food_times, long k) {
//음식의 양으로 HashMap을 생성합니다.
HashMap<Integer, List<Integer>> foodMap = new HashMap<>();
for (int i = 0; i < food_times.length; i++) {
if (foodMap.containsKey(food_times[i])){
foodMap.get(food_times[i]).add(i+1);
}else{
List<Integer> temp = new LinkedList<>();
temp.add(i+1);
foodMap.put(food_times[i],temp);
}
}
List<Integer> foodQuantList = foodMap.keySet().stream()
.sorted().collect(Collectors.toList());
long overTime = 0;
int priorQuant = 0;
Set<Integer> remains = IntStream.range(1,food_times.length+1).boxed().collect(Collectors.toSet()); // 전체 음식 set
//음식의 양 별로 따져서 k 값보다 해당 양까지 전부 먹는데 걸리는 시간이 작으면 다음 음식의 양으로 이동합니다.
// k 값보다 커지면 …
```
=> 무지의 먹방 라이브

tkdlqh2/20230314-tkdlqh2.md, tkdlqh2/20230316-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/42897
```java
public int solution(int[] money) {
int[] dp1 = new int[money.length];
dp1[0] = money[0];
dp1[1] = money[0];
for (int i = 2; i < money.length-1 ; i++) {
dp1[i] = Math.max(dp1[i-2]+money[i],dp1[i-1]);
}
int[] dp2 = new int[money.length];
dp2[0] = 0;
dp2[1] = money[1];
for (int i = 2; i < money.length-1; i++) {
dp2[i] = Math.max(dp2[i-2]+money[i],dp2[i-1]);
}
int answer = Math.max(dp1[money.length-2],dp2[money.length-3]+money[money.length-1]);
return Math.max(answer,dp2[money.length-2]);
}
}
```
간단한 dp 에 원 배열이 섞여 어렵게 느껴질 수 있으나 사실 이 문제도 생각해보면 굉장히 간단히 풀리는 문제입니다.(이것이 LEVEL 4라면 축복이야)
푸는 아이디어는 간단합니다. 첫번째 집과 마지막집의 경우를 미리 정해주는 것입니다.
첫번쨰 집을 털었다면 마지막집은 털어서는 안됩니다.
첫번째 집을 털지 않았다면 마지막집은 털어도 되고 안 털어도 됩니다.
dp1의 경우는 …
=> SOLVERTIC solve : 도둑질

tkdlqh2/20230314-tkdlqh2.md, tkdlqh2/20230315-tkdlqh2.md, tkdlqh2/20230316-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/12929
```java
public int solution(int n) {
return dfs(n,n);
}
public int dfs(int left, int right){
if(left == 0 && right == 0){
return 1;
}
int leftAnswer = 0;
if(left>=1){
leftAnswer = dfs(left-1,right);
}
int rightAnswer = 0;
if(right>=left+1){
rightAnswer = dfs(left,right-1);
}
return leftAnswer+rightAnswer;
}
}
```
특정 가짓수를 뻗어 나가는 문제는 dfs 문제라고 가정하고 문제를 전개해나가는 것이 맞는 것 같습니다. dfs 로 leftAnswer 와 rightAnswer 를 더해주는데 leftAnswer 는 왼쪽 괄호를 선택했을 때의 가짓수, rightAnswer 는 오른쪽 괄호를 선택했을 때의 가짓수입니다. leftAnswer 가 존재하기 위해서는 남아있는 왼쪽 괄호가 1개 이상이여야 하고, rightAnswer 가 존재하기 위해서는 남아있는 오른쪽 괄호가 왼쪽 괄호보다 1개 더 많거나 그 이상이여야합니다.
=> 올바른 괄호의 갯수

thewoowon/20230320-thewoowon.md
```python
from collections import deque
def solution(board):
answer = 0
R = len(board)
C = len(board[0])
rx, ry = 0, 0
for i in range(R):
for j in range(C):
if board[i][j]=='R':
rx, ry = i, j
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]
def bfs():
q = deque()
q.append((rx, ry))
visited = [[0]*C for _ in range(R)]
visited[rx][ry] = 1
while q:
px, py = q.popleft()
if board[px][py] == 'G':
return visited[px][py]
for i in range(4):
nx, ny = px, py
while True:
nx, ny = nx+dx[i], ny+dy[i]
if 0<=nx<R and 0<=ny<C and board[nx][ny]=='D':
nx -= dx[i]
ny -= dy[i]
break
if nx<0 or nx>=R or ny<0 or ny>=C:
nx -= dx[i]
ny -= dy[i]
break
if not visited[nx][ny]:
visited[nx][ny] = visited[px][py] + 1
q.append((nx, ny))
return -1
answer = bfs()
if answer > 0:
answer -= 1
return answer
```
"벽을 만나지 않으면 계속 직진하고, 그렇지 …
=> SOLVERTIC solve: 리코쳇 로봇

yg0585/20230320-yg0585.md
```java
import java.util.ArrayDeque;
public int solution(String[] board) {
int answer = 0;
boolean[][] visited = new boolean[board.length][board[0].length()];
int[] initCoord = findStart(board);
int[][] directs = {{1, 0}, {-1, 0}, {0, 1}, {0, -1}};
ArrayDeque<int[]> queue = new ArrayDeque<>();
queue.add(initCoord);
visited[initCoord[0]][initCoord[1]] = true;
while(!queue.isEmpty()) {
answer++;
int size = queue.size();
for (int i = 0; i < size; i++) {
int[] poll = queue.poll();
for (int j = 0; j < 4; j++) {
int[] tmp = poll.clone();
while(true) {
int dx = tmp[0] + directs[j][0];
int dy = tmp[1] + directs[j][1];
if (!isInRange(dx, dy, board) || isObstacle(dx, dy, board)) {
break;
}
tmp[0] = dx;
tmp[1] = dy;
}
if (board[tmp[0]].charAt(tmp[1]) == 'G')
return answer;
if …
```
=> SOLVERTIC solve : 리코쳇로봇

tkdlqh2/20230321-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/154538
```java
import java.util.HashSet;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Set;
public int solution(int x, int y, int n) {
if(x==y){return 0;}
PriorityQueue<List<Integer>> pq =new PriorityQueue<>((first,second)->{
if(first.get(1) ==second.get(1)){
return second.get(0) - first.get(0);
}else{
return first.get(1) - second.get(1);
}
});
Set<Integer> visited = new HashSet<>();
visited.add(x);
pq.add(List.of(x,0));
while(pq.size() != 0){
List<Integer> cur = pq.poll();
int num1 = cur.get(0)+n;
int num2 = cur.get(0)*2;
int num3 = cur.get(0)*3;
if(num1 == y){
return cur.get(1)+1;
}else if(!visited.contains(num1) && num1<y){
visited.add(num1);
pq.add(List.of(num1,cur.get(1)+1));
} …
```
=> 형진 - 숫자 변환하기

yg0585/20230321-yg0585.md
```java
import java.util.ArrayDeque;
public int solution(int x, int y, int n) {
int answer = 0;
boolean[] visited = new boolean[y + 1];
if (x==y)
return 0;
ArrayDeque<Integer> queue = new ArrayDeque<>();
queue.add(x);
while (!queue.isEmpty()) {
answer++;
int size = queue.size();
for (int i = 0; i < size; i++) {
int poll = queue.poll();
for (int k = 0; k < 3; k++) {
int ch = checkNum(poll, n, k);
if (ch == y) 
return answer;
if (ch > y)
continue;
if (!visited[ch]) {
queue.add(ch);
visited[ch] = true;
}
}
}
}
return -1;
}
private int checkNum(int num, int n, int k) {
if (k == 0) 
return num + n;
if (k == 1) 
return num * 2;
return num * 3;
}
}
```
어제 문제랑 똑같이 BFS로 풀이했습니다.
풀이 후 사람들의 풀이를 살펴보니 역시 
1. BFS풀이
2. DP풀이
이렇게 두가지 풀이가 대부분입니다.
dp 풀이는 보니까 6줄이면 끝나더라구요. 간단해서 좋은 것 같습니다.
=> SOLVERTIC solve: 숫자 변환하기

yg0585/20230322-yg0585.md
```java
class Solution
{
public int solution(String s) {
int answer = 1;
for (int i = 0; i < s.length(); i++) {
char c = s.charAt(i);
for (int j = s.length() - 1; j > i; j--) {
if (j + 1 - i < answer)
break;
if (s.charAt(j) == c) {
if (isPenlil(s.substring(i, j + 1)))
{
if (j + 1 - i > answer) {
answer = j + 1 - i;
break;
}
}
}
}
}
return answer;
}
private boolean isPenlil(String s) {
for (int i = 0; i < s.length(); i++) {
if (s.charAt(i) != s.charAt(s.length() - 1 - i))
return false;
}
return true;
}
}
```
오늘 문제도 무난했습니다. 주어진 S의 substring 들에서 가장 긴 대칭 문자열을 찾으면 되는 문제입니다.
아래와 같이 풀이했습니다.
1. 문자열의 앞부터 문자 하나씩 검사를 시작합니다.
2. 앞에서 검사를 시작한 문자와 같은 문자를 문자열의 뒤에서 찾습니다.
3. 같은 문자가 문자열에 뒤에도 존재한다면 앞 문자와 뒷 문자 사이의 문자열이 대칭인지 검사합니다.
이런 식으로 풀었다가 효율성에서 한 문제가 틀렸고, 그에 따라서 한 조건을 더 추가해줬습니다.
* 검사하게 될 문자열의 길이가 현재 찾은 대칭 …
=> SOLVERTIC solve: 가장 긴 팰린드롬

tkdlqh2/20230322-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/12904
```java
class Solution
{
public int solution(String s)
{
if(s.length() == 1){return 1;}
char[] arr = s.toCharArray();
int answer = 0;
for (int i = 0; i < arr.length-1; i++) {
next:for (int j = i; j < arr.length; j++) {
if(arr[i] == arr[j]){
int iClone = i;
int jClone = j;
while(iClone<jClone){
iClone++;
jClone--;
if(arr[iClone] != arr[jClone]){
continue next;
}
}
answer  = Math.max(answer,j-i+1);
}
}
}
return answer;
}
}
```
특별한 무언가를 한 것은 없습니다. 처음과 끝을 i,j 로 설정하면서 이중 for문을 돌고 
두 배열의 처음과 끝의 알파벳이 같으면 그 배열이 팰린드롬인지 check 합니다.
=> SOLVERTIC sovle : 가장 긴 팰린드롬

yg0585/20230324-yg0585.md
```java
import java.util.Scanner;
class Tornado {
int x = 0;
int y = 0;
int exX;
int exY;
int step = 0;
int step_size = 1;
int curretn_step_size = 0;
int direct = 0;
static int[][] directs = {{0, -1}, {1, 0}, {0, 1}, {-1, 0}};
int exdirect = 0;
boolean move() {
exX = x;
exY = y;
x += directs[direct][0];
y += directs[direct][1];
exdirect = direct;
curretn_step_size++;
if (curretn_step_size == step_size) {
direct = (direct + 1) % 4;
curretn_step_size = 0;
step++;
if (step % 2 == 0)
step_size++;
}
if (x == 0 && y == 0)
return true;
return false;
}
}
public class Main {
static int n;
static int[][] map;
static int sum = 0;
static Tornado tornado;
public static void main(String[] args) {
Scanner sc = new Scanner(System.in);
n = sc.nextInt();
map = new int[n][n];
for (int i = 0; i < n; i++) { …
```
=> SOLVERTIC solve: 마법사 상어와 토네이도

tkdlqh2/20230325-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/42861
```java
static int[] parents;
public int solution(int n, int[][] costs) {
int weightSum = 0;
Arrays.sort(costs,(x,y) -> x[2] -y[2]);
parents = new int[n+1];
for (int i = 0; i < parents.length; i++) {
parents[i] = i;
}
for (int i = 0; i < costs.length; i++) {
if(find(costs[i][0] )!= find(costs[i][1])){
union(costs[i][0],costs[i][1]);
weightSum += costs[i][2];
}
}
return weightSum;
}
public static int find(int a) {
if (a == parents[a]) {
return a;
}
return parents[a] = find(parents[a]);
}
public static void union(int a, int b){
int aP = find(a);
int bP = find(b);
if(aP != bP){
parents[aP] = bP;
}
}
}
```
이 문제 분류가 (프로그래머스 상에) greedy 라고 되어있는데 이 문제는 대표적인 최소 신장 트리 문제입니다.
최소 신장 트리에 대해서는 …
=> SOLVERTIC  solve  : 섬 연결하기

thewoowon/20230327-thewoowon.md
<자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기>
```mysql
SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS 
REGEXP '통풍시트|열선시트|가죽시트'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE
```
<조건에 맞는 도서와 저자 리스트 출력하기>
```mysql
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, date_format(BOOK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS BOOK
LEFT OUTER JOIN AUTHOR AS AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY BOOK.PUBLISHED_DATE
```
<조건에 부합하는 중고거래 상태 조회하기>
```mysql
SELECT BOARD_ID,WRITER_ID,TITLE,PRICE,
CASE WHEN STATUS = 'DONE' THEN '거래완료'
WHEN STATUS = 'RESERVED' THEN '예약중'
WHEN STATUS = 'SALE' THEN '판매중'
END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE='2022-10-05'
ORDER BY BOARD_ID DESC
```
<자동차 평균 대여 기간 구하기>
```mysql
SELECT CAR_ID AS CAR_ID, …
```
=> SOLVERTIC solve: SQL LV2 문제 모음

tkdlqh2/20230327-tkdlqh2.md
1. https://school.programmers.co.kr/learn/courses/30/lessons/151137
2. https://school.programmers.co.kr/learn/courses/30/lessons/144854
3. https://school.programmers.co.kr/learn/courses/30/lessons/164672
4. https://school.programmers.co.kr/learn/courses/30/lessons/157342
1. 
```mysql
SELECT rental.car_type,count(rental.car_type) as 'cars'
from CAR_RENTAL_COMPANY_CAR as rental
where rental.options like '%통풍시트%' or
rental.options like '%열선시트%' or
rental.options like '%가죽시트%'
group by car_type 
order by car_type;
```
2. 
```mysql
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK 
JOIN AUTHOR 
ON (BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID)
where book.category = '경제'
order by book.published_date;
```
3.
```mysql
select goods.board_id, …
```
=> SOLVERTIC solve: SQL LV2 문제 모음 - 형진

yg0585/20230329-yg0582.md
```sql
select ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
from ANIMAL_INS
join ANIMAL_OUTS on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
where ANIMAL_INS.SEX_UPON_INTAKE like '%Intact%'
and (ANIMAL_OUTS.SEX_UPON_OUTCOME like '%Spayed%' or ANIMAL_OUTS.SEX_UPON_OUTCOME like '%Neutered%')
order by ANIMAL_INS.ANIMAL_ID
```
```sql
select FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, sum(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT join FOOD_ORDER on FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
where  MONTH(FOOD_ORDER.PRODUCE_DATE) = 5 and YEAR(FOOD_ORDER.PRODUCE_DATE) = 2022
group by FOOD_PRODUCT.PRODUCT_ID
order by TOTAL_SALES desc, FOOD_PRODUCT.PRODUCT_ID asc
```
```sql
select CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
from …
```
=> SOLVERTIC solve: SQL LV.4

tkdlqh2/20230329-tkdlqh2.md
1. https://school.programmers.co.kr/learn/courses/30/lessons/59045
2. https://school.programmers.co.kr/learn/courses/30/lessons/131117
3. https://school.programmers.co.kr/learn/courses/30/lessons/131116
4. https://school.programmers.co.kr/learn/courses/30/lessons/62284
1. 보호소에서 중성화한 동물
```mysql
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.name 
from ANIMAL_INS join ANIMAL_OUTS on (ANIMAL_OUTS.animal_id = ANIMAL_INS.animal_id)
where ANIMAL_INS.SEX_UPON_INTAKE like "Intact%"
and (ANIMAL_OUTS.SEX_UPON_OUTCOME like "Spayed%" or
ANIMAL_OUTS.SEX_UPON_OUTCOME like "Neutered%");
```
2. 5월 식품들의 총매출 조회하기
```mysql
SELECT FOM.PRODUCT_ID,FP.PRODUCT_NAME ,FOM.TOTAL_AMOUNT*FP.PRICE AS TOTAL_SALES FROM (
SELECT FO.PRODUCT_ID, SUM(FO.AMOUNT) AS TOTAL_AMOUNT FROM FOOD_ORDER AS FO
WHERE …
```
=> Solvertic solve: SQL lv4 - tkdlqh2

thewoowon/20230403-thewoowon.md
```python
from collections import Counter
def solution(k, tangerine):
answer = 0
tangerine.sort()
count=Counter(tangerine)
for key,i in count.most_common():
temp = i
if k <= temp:
answer+=1
break
else:
k-=temp
answer+=1
return answer
```
most_common()라는 메소드를 먼저 이해하기 전에 Counter를 이해해야합니다.
Counter는 배열을 받아서 Counter 객체를 반환합니다.
Counter 객체는 배열의 요소를 key로, 요소의 개수를 value로 가지는 딕셔너리입니다.
그리고 most_common()은 Counter 객체의 메소드로, value를 기준으로 내림차순으로 정렬한 배열을 반환합니다.
그래서 most_common()을 사용하면, 가장 많은 개수를 가진 key부터 정렬된 배열을 얻을 수 있습니다.
void
=> FILMDOMS solve: 귤 고르기

yg0585/20230329-yg0582.md
```java
import java.util.*;
public int solution(int k, int[] tangerine) {
int answer = 0;
Map<Integer, Integer> map = new HashMap<>();
int total = tangerine.length;
for (int i = 0; i < total; i++)
map.put(tangerine[i], map.getOrDefault(tangerine[i], 0) + 1);
List<Map.Entry<Integer, Integer>> entries = new LinkedList<>(map.entrySet());
Collections.sort(entries, (o1, o2) -> o1.getValue().compareTo(o2.getValue()));
LinkedHashMap<Integer, Integer> result = new LinkedHashMap<>();
for (Map.Entry<Integer, Integer> entry : entries) {
result.put(entry.getKey(), entry.getValue());
}
int size = result.keySet().size();
for (int key : result.keySet()) {
total -= result.get(key);
size--;
if (total == k) {
return size;
}
else if(total < k) {
return size + 1;
}
}
return answer;
}
}
```
이 …
=> SOLVERTIC solve: 귤 고르기

tkdlqh2/20230404-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/154540
```java
import java.util.*;
static final int[][] DIR = {{1,0},{0,1},{-1,0},{0,-1}};
public int[] solution(String[] maps) {
char[][] mapsArr = new char[maps.length][maps[0].length()];
for (int i = 0; i < maps.length; i++) {
mapsArr[i] = maps[i].toCharArray();
}
LinkedList<Integer> answer = new LinkedList<>();
for (int i = 0; i < mapsArr.length; i++) {
for (int j = 0; j < mapsArr[0].length; j++) {
if(mapsArr[i][j] != 'X'){
int cur = dfs(mapsArr,i,j);
answer.add(cur);
}
}
}
if(answer.size() == 0){
return new int[]{-1};
}
return answer.stream().mapToInt(x->x).sorted().toArray();
}
int dfs(char[][] arr, int i, int j){
int answer = arr[i][j] - '0';
arr[i][j] = 'X';
for (int k = 0; k < 4; k++) {
int nextI = …
```
=> SOLVERTIC solve : 무인도 여행

yg0585/20230329-yg0582.md
```java
import java.util.Collections;
import java.util.PriorityQueue;
public long solution(int n, int[] works) {
long answer = 0;
PriorityQueue<Integer> queue = new PriorityQueue<>(Collections.reverseOrder());
for(int num : works) {
queue.add(num);
}
while(n > 0 && !queue.isEmpty()) {
int num = queue.poll() - 1;
if (num == 0) {
n--;
continue;
}
queue.add(num);
n--;
}
while (!queue.isEmpty()) {
int num = queue.poll();
answer += num * num;
}
return answer;
}
}
```
작업 분포가 비슷하게 분포되어 있어야 최소한의 피로도를 얻을 수 있습니다.
우선순위 큐를 사용해서 가장 높은 작업량 부터 1씩 작업하도록 했습니다.
=> SOLVERTIC solve: 야근 지수

tkdlqh2/20230404-tkdlqh2.md, tkdlqh2/20230405-tkdlqh2.md, tkdlqh2/20230406-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/12927
```java
import java.util.PriorityQueue;
import java.util.stream.Collectors;
public long solution(int n, int[] works) {
PriorityQueue<Integer> pq = new PriorityQueue<>((x,y) -> y-x);
pq.addAll(Arrays.stream(works).boxed().collect(Collectors.toList()));
for (int i = 0; i < n; i++) {
int cur = pq.poll();
if(cur >= 1){
pq.add(cur-1);
}
if(pq.size() == 0){return 0;}
}
long answer=0;
while(pq.size() != 0){
answer += pow(pq.poll());
}
return answer;
}
public long pow(int n){
return ((long) n) * ((long) n);
}
}
```
문제의 기본 아이디어는 큰 숫자들을 하나씩 빨리 까먹어야 합니다.
우선순위큐에다가 전체 list를 넣어주고 가장 큰 수 부터 1씩 까먹는 것을 n회 반복하고
큐에 남아 있는 숫자들을 모두 제곱수 처리해줘서 더해주면 됩니다.
처음에는 전체 합을 구하고 배열의 길이로 나눠서 구해줬는데 처음에 잘못 접근한 게 아쉽습니다.
=> tkdlqh2 - 야근 지수

thewoowon/20230404-thewoowon.md
```python
from collections import deque
dx, dy = [0, 0, -1, 1], [-1, 1, 0, 0]
def bfs(maps, i, j, visited):
visited[i][j] = 1
queue = deque([[i,j]])
count = 0
while queue:
i, j = queue.popleft()
count += int(maps[i][j])
for d in range(4):
x, y = i + dx[d], j + dy[d]
if not(0 <= x < len(maps) and 0 <= y < len(maps[0])): continue
if visited[x][y] == 0 and maps[x][y] != 'X':
queue.append([x, y])
visited[x][y] = 1
return count
def solution(maps):
answer = []
for i in range(len(maps)):
maps[i] = list(maps[i])
visited = [[0] * len(maps[0]) for _ in range(len(maps))]
for i in range(len(maps)):
for j in range(len(maps[0])):
if maps[i][j] != 'X' and visited[i][j] == 0:
answer.append(bfs(maps, i, j, visited))
if answer:
return sorted(answer)
else:
return [-1]
```
bfs를 활용한 전형적인 완탐 문제입니다.
메모이제이션을 …
=> SOLVERTIC solve: 무인도여행

thewoowon/20230406-thewoowon.md
```python
def solution(n, works):
if len(works) == 1:
if works[0]-n < 1:
return 0
else:
return (works[0]-n)**2
works.sort(reverse=True)
t = n
while t:
m = works[0]
for iter,value in enumerate(works):
if value == m:
works[iter] -= 1
t -= 1
if t == 0:
break
else:
break
return sum([i**2 if i >0 else 0 for i in works])
```
시소짝꿍보다 쉽게 풀렸습니다.
다 시간을 줄일 수 있는 포인트가 있을 것 같은데...
다시 찾아 봐야 할 것 같습니다.
=> SOLVERTIC solve: 야근지수

thewoowon/20230407-thewoowon.md
```python
def solution(sequence, k):
answer = [0,0]
n = len(sequence)
minimum = n
interval_sum = 0
end = 0
for start in range(n):
while interval_sum < k and end < n:
interval_sum += sequence[end]
end += 1    
if interval_sum == k:
if end-start == 1:
return [start,end-1]
if end-start == n:
return [start,end-1]
if end-start < minimum:
answer = [start,end-1]
minimum = end-start
interval_sum -= sequence[start]
return answer
```
부분 수열의 합을 구하는 문제입니다. 투 포인터를 활용하여 풀 수 있습니다.
투 포인터는 찌르면 바로 나올 정도로 익숙해져야 할 것 같습니다.
최악은 242.37ms 정도 나오는데, 더 빠르게 풀 수 있을 것 같습니다.
=> SOLVERTIC solve: 연속된 부분 수열의 합

tkdlqh2/20230412-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/43238
```java
public long solution(int n, int[] times) {
Arrays.sort(times);
long low = (long)times[0];
long high = (long)times[times.length-1]*(long)n;
while(low+1<high){
long mid = (low+high)/2;
if (check(mid,times,n)){
high = mid;
}else{
low = mid;
}
}
return high;
}
public boolean check(long time,int[]times,int n){
long possiblePeople = 0;
for(int i=0; i<times.length;i++){
possiblePeople += (time/(long)times[i]);
}
if(possiblePeople>=n){
return true;
}
return false;
}
}
```
이분 탐색으로 해당 시간에 사람을 최대 몇명까지 받을 수 있는지 계산하고 그 값이 n 이상이면 그 시간이 가능한 시간임을 check 할 수 있습니다. 이를 이분탐색으로 경우를 줄여 나가서 모든 사람이 심사를 받는데 걸리는 최소 시간을 구할 수 있습니다.
사실 예전에 풀었던 문제네요 ㅎㅎ
=> SOLVERTIC solve : 입국 심사

tkdlqh2/20230413-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/42898
```java
public int solution(int m, int n, int[][] puddles) {
if((m == 1 || n==1) &&  puddles[0].length == 0){
return 1;
} else if (m == 1 || n==1) {
return 0;
}
int[][] dp = new int[m+1][n+1];
for (int i = 0; i < puddles.length; i++) {
dp[puddles[i][0]][puddles[i][1]] = -1;
}
for (int i = 0; i < m+1; i++) {
if(dp[i][1] != -1){
dp[i][1] = 1;
}else{
break;
}
}
for (int i = 0; i < n+1; i++) {
if(dp[1][i] != -1){
dp[1][i] = 1;
}else{
break;
}
}
for (int i = 2; i < m+1; i++) {
for (int j = 2; j < n+1; j++) {
if(dp[i][j] != -1){
dp[i][j] = (Math.max(dp[i][j-1],0) + Math.max(dp[i-1][j],0))%1000000007;
}
}
}
return dp[m][n];
}
}
```
dp에다가 puddle의 위치에 -1 을 대입해서 표시해줍니다. 그리고 1행과 1열에 1을 대입하다가 중간에 puddle이 나오면 1을 대입하는 것을 …
=> SOLVERTIC solve : 등굣길

tkdlqh2/20230414-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/67259
```java
import java.util.PriorityQueue;
static final int[][] DIR = {{0,1},{1,0},{0,-1},{-1,0}};
public int solution(int[][] board) {
int[][][] visited = new int[board.length][board.length][4];
for (int i = 0; i < board.length; i++) {
for (int j = 0; j < board.length; j++) {
for (int k = 0; k < 4; k++) {
visited[i][j][k] = Integer.MAX_VALUE;
}
}
}
PriorityQueue<int[]> pq = new PriorityQueue<>((x,y) -> x[3]-y[3]);
for (int i = 0; i < 4; i++) {
visited[0][0][i] = 0;
pq.add(new int[]{0,0,i,0});
}
while(pq.size()!=0){
int[] cur = pq.poll();
int curRow = cur[0];
int curCol = cur[1];
int curDir = cur[2];
int curCost = cur[3];
for (int i = 0; i < 4; i++) {
int nextRow = curRow + DIR[i][0];
int nextCol = curCol …
```
=> SOLVERTIC solve :  경주로 건설

tkdlqh2/20230415-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/12971
```java
public int solution(int[] money) {
if(money.length == 1){
return money[0];
}else if(money.length == 2){
return Math.max(money[0],money[1]);
}
int[] dp1 = new int[money.length];
dp1[0] = money[0];
dp1[1] = money[0];
for (int i = 2; i < money.length-1 ; i++) {
dp1[i] = Math.max(dp1[i-2]+money[i],dp1[i-1]);
}
int[] dp2 = new int[money.length];
dp2[0] = 0;
dp2[1] = money[1];
for (int i = 2; i < money.length-1; i++) {
dp2[i] = Math.max(dp2[i-2]+money[i],dp2[i-1]);
}
int answer = Math.max(dp1[money.length-2],dp2[money.length-3]+money[money.length-1]);
return Math.max(answer,dp2[money.length-2]);
}
}
```
원 모양의 dp 문제로 예전에 풀었던 도둑질 문제와 같은 문제입니다.(https://school.programmers.co.kr/learn/courses/30/lessons/42897)
두 …
=> SOLVERTIC solve : 스티커 모으기(2)

tkdlqh2/20230422-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/12985
```java
class Solution
{
public int solution(int n, int a, int b)
{
int depth = 0;
while(n!=1){
n >>= 1;
depth++;
}
int sameSide = 0;
while(sameSide < depth){
if(side(a,depth,sameSide) == side(b,depth,sameSide)){
if(side(a,depth,sameSide) == 1){
a -= 2 << (depth-sameSide-1);
b -= 2 << (depth-sameSide-1);
}
sameSide++;
}else{
break;
}
}
return depth-sameSide+1;
}
public int side(int a, int depth, int matchCount){
return a > 2 << (depth-matchCount-1) ? 1:0;
}
}
```
N 에 따라 총 match 의 깊이가 달라지고, 각 숫자에 1을 빼고 이를 bit 로 나타냈을 때, 앞에 자릿수부터 숫자가 얼마나 일치하느냐에 따라 정답이 달라집니다. 
N이 8 ,A 가 4, B 가 7 인 경우에 대해 N이 8이면 8=2^3 이기에 그 깊이는 3+1인 4가 됩니다. A 는 bit 로 나타내면 3 -> 011 이 되고 B 는 6 -> 110 입니다. 앞에 자릿수부터 비교하면 0과 1이므로 이미 여기서 다른편에 위치합니다. 따라서 만나기 위한 매치수는 3-0 …
=> SOLVERTIC solve : 예상대진표

tkdlqh2/20230423-tkdlqh2.md
https://school.programmers.co.kr/learn/courses/30/lessons/12953
```java
public int solution(int[] arr) {
return Arrays.stream(arr).reduce((x,y) -> {
if(x>y){
return lcm(x,y);
}else{
return lcm(y,x);
}
}).getAsInt();
}
public int gcd(int a, int b){
int bigger = Math.max(a,b);
int lower = Math.min(a,b);
if(bigger%lower == 0){
return lower;
}
return gcd(lower,bigger%lower);
}
public int lcm(int a, int b){
return a*b/gcd(a,b);
}
}
```
2개의 최소공배수 구하는 것을 stream 의 reduce 를 활용해서 계속 적용하면서 한 개의 최소공배수로 만듭니다. 최소공배수를 구하는 것은 두수의 곱/최대공약수 로 구하고 최대 공약수는 유클리드 호제법으로 구합니다.
=> SOLVERTIC solve : N 개의 최소공배수
